app:
  description: "welcome to ${app.name}"
  name: My app
connection: "{connectionString:'http://__', userName:'foo',password:'pass'}"
db:
  host: 127.01.2.01
  port: 1302
  values:
    connectionString: "http://__"
    password: "pass"
    userName: "foo"
listValues: one, two,three
my:
  greeting: Hello world
spring:
  cloud:
    config:
      uri: http://localhost:8888  
#spring:
#   config:
#       import: optional:configserver:http:localhost:8888

#spring:
#  profiles:
#    active: test