
package com.javabrains;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestMartCatalogService", targetNamespace = "http://javabrains.com/", wsdlLocation = "http://localhost:1234/productcatalog?wsdl")
public class TestMartCatalogService
    extends Service
{

    private final static URL TESTMARTCATALOGSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTMARTCATALOGSERVICE_EXCEPTION;
    private final static QName TESTMARTCATALOGSERVICE_QNAME = new QName("http://javabrains.com/", "TestMartCatalogService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/productcatalog?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTMARTCATALOGSERVICE_WSDL_LOCATION = url;
        TESTMARTCATALOGSERVICE_EXCEPTION = e;
    }

    public TestMartCatalogService() {
        super(__getWsdlLocation(), TESTMARTCATALOGSERVICE_QNAME);
    }

    public TestMartCatalogService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTMARTCATALOGSERVICE_QNAME, features);
    }

    public TestMartCatalogService(URL wsdlLocation) {
        super(wsdlLocation, TESTMARTCATALOGSERVICE_QNAME);
    }

    public TestMartCatalogService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTMARTCATALOGSERVICE_QNAME, features);
    }

    public TestMartCatalogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestMartCatalogService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestMartCatalog
     */
    @WebEndpoint(name = "TestMartCatalogPort")
    public TestMartCatalog getTestMartCatalogPort() {
        return super.getPort(new QName("http://javabrains.com/", "TestMartCatalogPort"), TestMartCatalog.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestMartCatalog
     */
    @WebEndpoint(name = "TestMartCatalogPort")
    public TestMartCatalog getTestMartCatalogPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://javabrains.com/", "TestMartCatalogPort"), TestMartCatalog.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTMARTCATALOGSERVICE_EXCEPTION!= null) {
            throw TESTMARTCATALOGSERVICE_EXCEPTION;
        }
        return TESTMARTCATALOGSERVICE_WSDL_LOCATION;
    }

}
